[package]
name = "canon"
version = "0.1.0"
authors = ["pgattic <pgattic@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.1", features = ["router"] }
libcanon = { path = "crates/libcanon" }
dioxus-logger = "0.6.1"
dirs = "5.0.1"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

# force vendored openssl on android
[target.'cfg(target_os = "android")'.dependencies]
git2 = { version = "0.19.0", features = ["vendored-libgit2", "vendored-openssl"]}

